### ISSUE TITLE
no such method error: closeQuietly

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#330] opened 2015-07-20 17:26 UTC
Sergei Iakhnin (I believe @llevar on github) reports seeing this when running Guacamole:

```
2015-07-16 16:37:16 ERROR Executor:96 - Exception in task 1.0 in stage 1.0 (TID 5)

java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.closeQuietly(Ljava/io/Closeable;)V

at org.apache.hadoop.hdfs.DFSInputStream.getBlockReader(DFSInputStream.java:1186)

at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:575)

at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:792)

at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:839)

at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:644)

at java.io.FilterInputStream.read(FilterInputStream.java:83)

at org.seqdoop.hadoop_bam.SAMFormat.inferFromData(SAMFormat.java:53)

at org.seqdoop.hadoop_bam.AnySAMInputFormat.getFormat(AnySAMInputFormat.java:147)

at org.seqdoop.hadoop_bam.AnySAMInputFormat.createRecordReader(AnySAMInputFormat.java:179)

at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:131)

at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:104)

at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:66)

at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)

at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)

at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)

at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)

at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)

at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)

at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)

at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)

at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)

at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)

at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)

at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)

at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)

at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:70)

at org.apache.spark.rdd.RDD.iterator(RDD.scala:242)

at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)

at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)

at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)

at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)

at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)

at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)

at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)

at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)

at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)

at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)

at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)

at org.apache.spark.scheduler.Task.run(Task.scala:64)

at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

**Comment by hammer** [comment] 2015-07-20 17:29
Smells like a version mismatch

**Comment by arahuja** [comment] 2015-07-20 17:33
Sorry we chatted offline, this was due to passing and HDFS was input while running in local mode.

This can be resolved by passing a local file path in local mode, or setting up `HADOOP_CONF_DIR` or `YARN_CONF_DIR` when runnning Spark distrbuted as described in https://spark.apache.org/docs/latest/running-on-yarn.html

**Comment by hammer** [comment] 2015-07-20 17:34
@arahuja can we improve the error message before closing?

**Comment by llevar** [comment] 2015-07-20 17:44
If you guys don't mind not closing this just yet, perhaps we can get the real root cause. What unblocked me was not executing the code path that results in the error, not fixing the error itself. Unless, HDFS is explicitly not supported as a data source in local mode.

I think this is definitely a library version issue, so I am just getting the list of versions together for your information.

**Comment by llevar** [comment] 2015-07-20 17:54
Spark version - 1.3.0
Hadoop version - 2.6.0
Guacamole version - master

**Comment by llevar** [comment] 2015-07-20 19:13
Well, I did a little more digging. Guacamole master is built against hadoop 2.3 as specified in the pom file. I assume there was an incompatible API change between 2.3 and later versions (I'm running 2.6). After pointing the pom file to 2.4 another error appeared:

```
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:379)
  at org.seqdoop.hadoop_bam.AnySAMInputFormat.getSplits(AnySAMInputFormat.java:219)
  at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:95)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
  at scala.Option.getOrElse(Option.scala:120)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:32)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
```
Now, this one appears to be related to more API incompatibilities between Hadoop and the Google Guava library. It appears that this library is shadowed by the ADAM folks' (or maybe your own?) class, as the pom file has this configuration:
```xml
          <relocation>
             <pattern>com.google.common</pattern>
              <shadedPattern>org.bdgenomics.guavarelocated</shadedPattern>
              <includes>
                <include>com.google.common.**</include>
              </includes>
            </relocation> 
```

By commenting this out and dropping the guava version back from 18.0 (version in the current pom) to 16.0 (latest version that has the referenced StopWatch API) I was able to successfully compile guacamole and run using my initial command against HDFS 2.6.

This looks like a bit of a versioning mess so I'll leave it to you folks to sort out what's best for your tool, but for the time being I'll run against the local filesystem.

**Comment by ryan-williams** [comment] 2016-08-20 04:21
I think that we shade in the conflicting Guava things correctly now, that code has gone through some paces since the last activity here. I'm going to close this but feel free to reopen if anyone sees this again!

**Closed by ryan-williams** 2016-08-20 04:21 UTC
